# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef418b5899a446131925b7f38b9710ee43fb069b5f33cd69e7ddf0f25417b73f208d40b6066f840bffb2fbd67cae4446df749cb76718bcbd1a147658934fd3d

test:
  secret_key_base: a7d8d5e9193c23f8027a6ba17b67c84d3995831bef12e1be8635fa28b0af37365db2d638d7d319eb97f31ff1e7aa650a1d0d8167eda3ce0559fcb29a42082655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
